# Generated by Django 3.1 on 2020-08-30 09:57

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('slug', models.SlugField(blank=True, max_length=400, unique=True)),
                ('description', models.TextField()),
                ('body', tinymce.models.HTMLField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('comments', models.CharField(choices=[('ENABLE', 'Enable'), ('Disable', 'Disable')], default='ENABLE', max_length=10)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'My College Only')], default='PRIVATE', max_length=10)),
                ('college_visibility', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='YES', max_length=10)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
                ('user_create', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PostDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('slug', models.SlugField(blank=True, max_length=400, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('directory', models.ManyToManyField(blank=True, to='post.Post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
