# Generated by Django 3.1 on 2020-09-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200902_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'My College Only'), ('PUBLIC', 'Public')], default='PRIVATE', max_length=10),
        ),
    ]
