# Generated by Django 3.1 on 2020-09-05 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20200905_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='college_visibility',
        ),
    ]
