# Generated by Django 3.1 on 2020-09-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_remove_post_college_visibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_created',)},
        ),
    ]
