# Generated by Django 3.1 on 2020-09-07 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200831_1432'),
        ('post', '0009_auto_20200907_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdirectory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='user.profile'),
        ),
    ]
