# Generated by Django 3.1 on 2020-09-07 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20200907_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postdirectory',
            options={'ordering': ('-date_created',)},
        ),
    ]
