# Generated by Django 3.1 on 2020-08-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20200830_1527'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='like',
            table='Likes',
        ),
        migrations.AlterModelTable(
            name='saved',
            table='Saved_Items',
        ),
    ]
