# Generated by Django 3.1 on 2020-09-05 03:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20200905_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked',
        ),
        migrations.AddField(
            model_name='like',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
