# Generated by Django 3.1 on 2020-09-06 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_auto_20200905_0923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saved',
            options={'ordering': ('-date_created',)},
        ),
    ]
