# Generated by Django 3.1 on 2020-08-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200830_1527'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='Project',
        ),
        migrations.AlterModelTable(
            name='projectbanner',
            table='Project_Banners',
        ),
    ]
