# Generated by Django 3.1 on 2020-09-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200830_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'My College Only'), ('PUBLIC', 'Public')], default='PRIVATE', max_length=10),
        ),
    ]
