# Generated by Django 3.1 on 2020-09-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200903_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='comments',
            field=models.CharField(choices=[('ENABLE', 'Enable'), ('DISABLE', 'Disable')], default='ENABLE', max_length=10),
        ),
    ]
