# Generated by Django 3.1 on 2020-09-06 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_project_college_visibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectbanner',
            options={'ordering': ('-date_created',)},
        ),
    ]
