# Generated by Django 3.1 on 2020-09-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20200906_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-date_created',)},
        ),
    ]
