# Generated by Django 3.1 on 2020-09-16 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200831_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'ordering': ('name',)},
        ),
    ]
