# Generated by Django 3.1 on 2020-09-04 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20200904_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ('-date_created',)},
        ),
    ]
